CREATE TABLE [dbo].[TempFanFactors]
(
[DimCustomerId] [int] NULL,
[SourceDB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [date] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cust_Priority] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimary_Zip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimary_State] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimary_Colorado_Flag] [int] NULL,
[WaitList_Flag] [int] NULL,
[UpdatedDate] [datetime] NULL,
[IsDeleted] [int] NULL,
[Email_Opened_Flag] [int] NULL,
[Email_Open_MostRecent] [datetime] NULL,
[Email_Open_Qty] [int] NULL,
[Form_Submit_Flag] [int] NULL,
[Form_Submit_Qty] [int] NULL,
[CrushMember_Flag] [int] NULL,
[BunchMember_Flag] [int] NULL,
[EmailGroup_OrangeJuice] [int] NULL,
[EmailGroup_OrangeHerd] [int] NULL,
[EmailGroup_ICYMI] [int] NULL,
[EmailGroup_SurveyPanel] [int] NULL,
[EmailGroup_BroncosPromos] [int] NULL,
[EmailGroup_Stadium] [int] NULL,
[EmailGroup_Outlaws] [int] NULL,
[EmailGroup_Memberships_Total] [int] NULL,
[NonGameEvents_Total] [int] NULL,
[ContestsEntered_Total] [int] NULL,
[Tickets_LastPurchase_Date] [datetime] NULL,
[Tickets_DaysSince_LastPurchase] [int] NULL,
[Tickets_TotalPaid] [decimal] (38, 6) NULL,
[Tickets_TotalQty] [int] NULL,
[Suite_Club_Flag] [int] NULL,
[LicenseFees_TotalPaid] [decimal] (38, 6) NULL,
[OrigPrice_Total] [numeric] (38, 2) NULL,
[ResalePrice_Total] [numeric] (38, 0) NULL,
[MarkupPaid_Total] [numeric] (38, 0) NULL,
[Tickets_Attendance_Three_Years] [int] NULL,
[Tickets_Attendance_One_Year] [int] NULL,
[Tickets_Attendance_MostRecent_Date] [datetime] NULL,
[Attended_TrickOrTreat] [int] NULL,
[Attended_TD_HOF_Celebration] [int] NULL,
[Attended_HolidayPhoto] [int] NULL,
[Fanatics_MaxOrderDate] [datetime] NULL,
[Fanatics_TotalSpent_30Days] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_90Days] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_Year] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_LifeTime] [decimal] (38, 6) NULL,
[WooCommerce_MaxOrderDate] [datetime] NULL,
[WooCommerce_TotalSpent_30Days] [float] NULL,
[WooCommerce_TotalSpent_90Days] [float] NULL,
[WooCommerce_TotalSpent_Year] [float] NULL,
[WooCommerce_TotalSpent_LifeTime] [float] NULL,
[Sunday_ticket] [int] NULL,
[Fantasy] [int] NULL,
[Pickem] [int] NULL
)
GO
