CREATE TABLE [dbo].[FanFactorsTemp_AMEITIN]
(
[DimCustomerId] [int] NOT NULL,
[SourceDB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [date] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimary_Zip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimary_State] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Colorado_PrimaryAddress_Flag] [int] NOT NULL,
[WaitList_Flag] [int] NOT NULL,
[UpdatedDate] [datetime] NOT NULL,
[IsDeleted] [bit] NOT NULL,
[Email_Opened] [int] NOT NULL,
[Most_Recent_Email_Open] [datetime] NULL,
[Number_Emails_Opened] [int] NULL,
[FormSubmit_Flag] [int] NOT NULL,
[Number_Forms_Submitted] [int] NULL,
[CrushMember_Flag] [int] NOT NULL,
[BunchMember] [int] NOT NULL,
[OrangeJuice] [int] NOT NULL,
[OrangeHerd] [int] NOT NULL,
[ICYMI] [int] NOT NULL,
[SurveyPanel] [int] NOT NULL,
[BroncosPromos] [int] NOT NULL,
[Stadium] [int] NOT NULL,
[Outlaws] [int] NOT NULL,
[Arcade] [int] NULL,
[Barclays_2016] [int] NULL,
[Best_Seats_in_the_House] [int] NULL,
[Bike_to_Work] [int] NULL,
[BMW] [int] NULL,
[Broncos_Bud_Light] [int] NULL,
[Broncos_Bud_Light__Ring_of_Fame_Contest] [int] NULL,
[Broncos_Bud_Light_Facebook] [int] NULL,
[Broncos_Bud_Light_Ticket_Giveaway] [int] NULL,
[Broncos_Budlight_Various_Contests] [int] NULL,
[Broncos_Fanaticos] [int] NULL,
[Bud_Light_Draft] [int] NULL,
[Bud_Light_Up_for_Whatever_Contest] [int] NULL,
[BWW] [int] NULL,
[Canon_Shoot_Like_a_Pro_Contests] [int] NULL,
[Carmax_2017] [int] NULL,
[Carmax_VIP] [int] NULL,
[CenturyLink_2017] [int] NULL,
[CenturyLink_Dinner_with_a_Draft_Pick] [int] NULL,
[Denver_Broncos_Kickoff_Kid] [int] NULL,
[Dia_del_Nino] [int] NULL,
[DirecTV_Fan_Fly_In] [int] NULL,
[DirecTV_Fantasy_Football_Party] [int] NULL,
[DirecTV_Fly_In] [int] NULL,
[DirecTV_Fly_In_2015] [int] NULL,
[En_tu_Casa] [int] NULL,
[Espanol_Prize_Registration] [int] NULL,
[Facebook_Ticket_Giveaway_Broncos_vs_Colts] [int] NULL,
[Famous_Daves_Mini_Miles_Entries] [int] NULL,
[Fan_Pack] [int] NULL,
[Fanaticos_Fathers_Day] [int] NULL,
[Fanaticos_Giveaway] [int] NULL,
[Fast_Dash] [int] NULL,
[Free_Tickets] [int] NULL,
[Gameday_2016_Season] [int] NULL,
[Gameday_Preview] [int] NULL,
[Grease_Monkey_2017] [int] NULL,
[Guess_the_Schedule] [int] NULL,
[Hackathon] [int] NULL,
[HelmetForHelmet] [int] NULL,
[Indi.com] [int] NULL,
[Jack_Black] [int] NULL,
[Kickoff_Kid] [int] NULL,
[King_Soopers] [int] NULL,
[Kwal_Paint_Winner] [int] NULL,
[Levis] [int] NULL,
[Mcdonalds_key_tag] [int] NULL,
[McDonalds_Playoffs] [int] NULL,
[Panini] [int] NULL,
[Papa_johns] [int] NULL,
[Playoff_Tickets] [int] NULL,
[Posada] [int] NULL,
[Salute_to_Fans_Vote] [int] NULL,
[SB50_Ring_Digital] [int] NULL,
[SB50_Tickets] [int] NULL,
[SB50_VIP] [int] NULL,
[social] [int] NULL,
[thankyoufans] [int] NULL,
[United_in_OrangeHelmet_Hunt] [int] NULL,
[Von_Miller_Contest] [int] NULL,
[Web_Contest] [int] NULL,
[Westrock] [int] NULL,
[What_Would_You_Do_for_Broncos_Playoff_Tickets] [int] NULL,
[Xcel_Energy_Draft] [int] NULL,
[Xome_Playoffs] [int] NULL,
[Yahoo_Fantasy] [int] NULL,
[45_day_challenge] [int] NULL,
[45_Day_Fitness_Fall_2016] [int] NULL,
[All_You_Can_Eat_Tailgate] [int] NULL,
[Broadnet_2017] [int] NULL,
[Broncos_7K_2015] [int] NULL,
[Broncos_7K_Registration_2014] [int] NULL,
[Broncos_Bunch_Movie_Night] [int] NULL,
[Broncos_Bunch_Trick_or_Treat] [int] NULL,
[Bunch_Kids_Day] [int] NULL,
[Bunch_Movie_Night_RSVP] [int] NULL,
[Bunch_Movie_Night_RSVP_2016] [int] NULL,
[Bunch_Summer_Kickoff_RSVP] [int] NULL,
[Bunch_training_camp] [int] NULL,
[Bunch_trick_of_treat] [int] NULL,
[Carne_Asada_Flea_Market_2017] [int] NULL,
[Carne_Asada_Greeley_2017] [int] NULL,
[Crush_Night_Out] [int] NULL,
[Denver_7K_2017] [int] NULL,
[Espanol] [int] NULL,
[Espanol_2017] [int] NULL,
[Expo_2016] [int] NULL,
[Expo_2017] [int] NULL,
[Expo_Survey_collect] [int] NULL,
[Fan_Forum] [int] NULL,
[Greeley_Salute_to_Fans] [int] NULL,
[Mountain_Village_2016] [int] NULL,
[Mountain_Village_2017] [int] NULL,
[Orange_County] [int] NULL,
[Philadelphia] [int] NULL,
[Salute_to_Fans] [int] NULL,
[Salute_to_Fans_2016] [int] NULL,
[Training_Camp_2016] [int] NULL,
[Training_Camp_2017] [int] NULL,
[Tickets_LastPurchase_Date] [datetime] NULL,
[Tickets_DaysSince_LastPurchase] [int] NULL,
[Tickets_TotalPaid] [decimal] (38, 6) NULL,
[Tickets_TotalQty] [int] NULL,
[Tickets_Attendance_Three_Years] [int] NULL,
[Tickets_Attendance_One_Year] [int] NULL,
[Tickets_Attendance_MostRecent_Date] [datetime] NULL,
[Attended_TrickOrTreat] [int] NULL,
[Attended_TD_HOF_Celebration] [int] NULL,
[Attended_HolidayPhoto] [int] NULL,
[Fanatics_MaxOrderDate] [datetime] NULL,
[Fanatics_TotalSpent_30Days] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_90Days] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_Year] [decimal] (38, 6) NULL,
[Fanatics_TotalSpent_LifeTime] [decimal] (38, 6) NULL,
[WooCommerce_MaxOrderDate] [datetime] NULL,
[WooCommerce_TotalSpent_30Days] [float] NULL,
[WooCommerce_TotalSpent_90Days] [float] NULL,
[WooCommerce_TotalSpent_Year] [float] NULL,
[WooCommerce_TotalSpent_LifeTime] [float] NULL,
[Sunday_ticket] [int] NULL,
[Fantasy] [int] NULL,
[Pickem] [int] NULL
)
GO
