CREATE TABLE [src].[TurnKey_DemographicAppend]
(
[ProspectID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abilitec ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Female] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Male] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Unknown Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Female] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Male] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Unknown Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Female] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Male] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Unknown Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Female] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Male] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Unknown Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Female] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Male] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Unknown Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - Input Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Owner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - Input Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 18-24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 25-34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 35-44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 45-54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 55-64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 65-74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 75+] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name - 1st Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - 1st Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - Input Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Owner   Renter] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income - Estimated Household] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InfoBase Positive Match Indicator] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length of Residence] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Buyer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Donor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Responder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 18-24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 25-34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 35-44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 45-54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 55-64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 65-74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 75+] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital Status in the Household] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Initial - 1st Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Sources] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Input Individual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Match Indicator] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Presence of Children] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suppression - Mail - DMA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 18-24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 25-34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 35-44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 45-54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 55-64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 65-74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 75+] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Working Woman] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
