CREATE TABLE [src].[FanaticsReview]
(
[Order_ID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_First_Name] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_Last_Name] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_Email] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailOptIn] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Date] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductCategory] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductSubCategory] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtySold] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitPrice] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderDiscountTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderGrossSubTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderTaxableSubTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderNonTaxableSubTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderTaxTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderNetTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderShipTotal] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total_Of_Sale_Paid_By_Account_Order] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderPromo] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddress0] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddress1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddress2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressCity] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressState] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressCounty] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressZip] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressTel] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressAttention] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddress0] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddress1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddress2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddressCity] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddressState] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilAddressCountry] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddressZip] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsTeamShop] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
